name: send slack message
on:
  issues: [created]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: post slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          slack-message: |
              "The URL of the newly created issue is: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }} created."
          channel-id: ${{ vars.slack_channel }}
