name: Model Test on push
on:
  push: 
    branches: ['main']
  workflow_dispatch:
  
jobs:

  test:
    if: github.repository != 'ersilia-os/eos-template'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
          
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        id: create_issue 
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{ vars.test_issue_title }}
          assignees: |
            $(echo "${{ vars.assignees }}" | tr '\n' ' ' | awk '{split($0,a," "); print a[int(rand()*(NR+1))]}')
          body: |
            ## Test Issue $(echo "${{ vars.assignees }}" | tr '\n' ' ' | awk '{split($0,a," "); print a[int(rand()*(NR+1))]}')
          labels: |
            test
