name: Model Test on push
on:
  push: 
    branches: ['main']
  workflow_dispatch:
  
jobs:

  test:
    if: github.repository != 'ersilia-os/eos-template'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Shuffle assignees
        id: shuffle
        run: |
          export assignees=$(echo "${{ vars.assignees }}" | awk 'BEGIN {FS=","}; {srand();split($0,a,FS); print a[int(rand()*NF+1)]}')
          echo "::set-output name=shuffled_assignee:: $assignees"
          
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        id: create_issue 
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{ vars.test_issue_title }}
          assignees: ${{ steps.shuffle.outputs.shuffled_assignee }}
          body: |
            ## Test Issue ${{ steps.shuffle.outputs.shuffled_assignee }}
          labels: |
            test
